services:

    olix.formsext.twig.extension.form:
        class: Olix\FormsExtBootstrapBundle\Twig\Extension\FormExtension
        arguments: [ "@twig.form.renderer" ]
        tags:
            - { name: twig.extension }

    olix.formsext.type.switch:
        class: Olix\FormsExtBootstrapBundle\Form\Type\SwitchType
        tags:
            - { name: form.type, alias: olix_switch }
