services:

    olix.formsext.twig.extension.form:
        class: Olix\FormsExtBootstrapBundle\Twig\Extension\FormExtension
        arguments: [ "@twig.form.renderer" ]
        tags:
            - { name: twig.extension }

    olix.formsext.type.switch:
        class: Olix\FormsExtBootstrapBundle\Form\Type\SwitchType
        tags:
            - { name: form.type, alias: olix_switch }
    olix.formsext.type.datepicker:
        class: Olix\FormsExtBootstrapBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: olix_datepicker }
    olix.formsext.type.timepicker:
        class: Olix\FormsExtBootstrapBundle\Form\Type\TimePickerType
        tags:
            - { name: form.type, alias: olix_timepicker }
    olix.formsext.type.datetimepicker:
        class: Olix\FormsExtBootstrapBundle\Form\Type\DateTimePickerType
        tags:
            - { name: form.type, alias: olix_datetimepicker }
    olix.formsext.type.select2_choice:
        class: Olix\FormsExtBootstrapBundle\Form\Type\Select2Type
        arguments: [ "choice" ]
        tags:
            - { name: form.type, alias: olix_select2_choice }
    olix.formsext.type.select2_entity:
        class: Olix\FormsExtBootstrapBundle\Form\Type\Select2Type
        arguments: [ "entity" ]
        tags:
            - { name: form.type, alias: olix_select2_entity }
    olix.formsext.type.select2_country:
        class: Olix\FormsExtBootstrapBundle\Form\Type\Select2Type
        arguments: [ "country" ]
        tags:
            - { name: form.type, alias: olix_select2_country }
    olix.formsext.type.select2_language:
        class: Olix\FormsExtBootstrapBundle\Form\Type\Select2Type
        arguments: [ "language" ]
        tags:
            - { name: form.type, alias: olix_select2_language }
    olix.formsext.type.select2_locale:
        class: Olix\FormsExtBootstrapBundle\Form\Type\Select2Type
        arguments: [ "locale" ]
        tags:
            - { name: form.type, alias: olix_select2_locale }
    olix.formsext.type.select2_timezone:
        class: Olix\FormsExtBootstrapBundle\Form\Type\Select2Type
        arguments: [ "timezone" ]
        tags:
            - { name: form.type, alias: olix_select2_timezone }
    olix.formsext.type.select2_currency:
        class: Olix\FormsExtBootstrapBundle\Form\Type\Select2Type
        arguments: [ "currency" ]
        tags:
            - { name: form.type, alias: olix_select2_currency }
    olix.formsext.type.select2_hidden:
        class: Olix\FormsExtBootstrapBundle\Form\Type\Select2Type
        arguments: [ "hidden" ]
        tags:
            - { name: form.type, alias: olix_select2_hidden }
    olix.formsext.type.doublelist_choice:
        class: Olix\FormsExtBootstrapBundle\Form\Type\DoubleListType
        arguments: [ "choice" ]
        tags:
            - { name: form.type, alias: olix_doublelist_choice }
    olix.formsext.type.doublelist_entity:
        class: Olix\FormsExtBootstrapBundle\Form\Type\DoubleListType
        arguments: [ "entity" ]
        tags:
            - { name: form.type, alias: olix_doublelist_entity }

